config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  mount ActionCable.server => '/cable'

  root controller: :home, action: :index

  resource :admin, controller: 'admin' do
    get :auto_logout
  end

  resource :home, controller: 'home' do
    match :login, via: [:get, :post]
    delete :logout
    get :publish_number
    get :publish_backup
    get :reset_cart, format: :js
    get :read
    get :account_details
  end
  resources :account_activities

  resources :reports do
    collection do
      get :detailed_z_report
      get :zreport

    end
  end

  resources :line_items do
    member do
      post :cancel
    end
  end

  resources :orders do
    collection do
      post :complete
      post :populate
      delete :remove_item
    end
    member do
      post :cancel
      post :print
    end
  end
  resources :accounts
  resources :products do
    collection do
      post :update_positions
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :account_required!, only: [:account_details]
  before_action :session_expiry, only: [:account_details]
  before_action :update_activity_time, only: [:account_details]

  def index
    @products = Product.includes(:image_attachment, :image_blob).active.order('position').to_a
    @order = current_order(false)
    @products_to_hide = []
    @order.line_items.group(:product_id).count.each do |pid, count|
      p = @products.select { |p| (p.id == pid) && p.count_on_hand <= count }
      @products_to_hide << p[0].id if p && p[0]
    end if @order
  end

  def reset_cart
    @order = current_order
    if @order
      @product_ids_to_show = @order.line_items.pluck(:product_id)
    end
    session.delete :order_id
    @order = nil
    respond_to do |format|
      format.js
    end
  end

  def account_details
    if @current_account && @current_account.admin? && params[:id].present?
      @account = Account.find(params[:id])
    else
      @account = @current_account
    end
    @account_activities = @account.account_activities.page(params[:page]).order(:created_at => :desc)
  end

  def publish_number
    account_id = Account.where(card: params[:card]).first.try(:id)
    ActionCable.server.broadcast 'rfid_read',
                                 card: params[:card], account_id: account_id
    render text: 'ok'
  end

  def publish_backup
    ActionCable.server.broadcast 'publish_backup', status: params[:status]
    render text: 'ok'
  end


  def read

  end

  def login
    unless request.get?
      if params[:card].present?
        account = Account.where(card: params[:card]).first
        if account
          session[:account_id] = account.id
        else
          flash['warning'] = "Kart tanımlanamadı..."
          redirect_to root_path and return
        end
      end
      redirect_to account_details_home_path
    end
  end

  def logout
    session.delete :account_id
    flash[:success] = "Çıkış yapıldı"
    redirect_to root_path
  end

end

app/views/home/account_details.html.erb
<h2><%= @account.name %> <small class="balanceText <%= @account.balance_health %>">Bakiyeniz: ₺ <%= @account.balance.to_f.round(2) %></small></h2>

<%- model_class = AccountActivity -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= 'Kaynak' %></th>
    <th><%= model_class.human_attribute_name(:amount) %></th>
    <th><%= t :created_at %></th>
    <th>İşlemi yapan</th>
  </tr>
  </thead>
  <tbody>
  <% @account_activities.each do |account_activity| %>
      <tr>
        <td><%= link_to(account_activity.source.try(:name), url_for(account_activity.source)) rescue '' %></td>
        <td class="<%= account_activity.amount > 0 ? 'success' : 'danger' %>">₺<%= account_activity.amount.to_f %></td>
        <td><%=l account_activity.created_at %></td>
        <td><%= account_activity.admin.try(:name) || '-' %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @account_activities,:theme => 'twitter-bootstrap-3' %>

app/views/home/index.html.erb
<div class="productArea">

  <ul class="productList">
    <% @products.each do |product| %>
        <li onclick="$(this).find('form').trigger('submit');" id="product_<%= product.id %>" style="display: <%= @products_to_hide.include?(product.id) ? 'none' : 'inherit' %>">
          <div class="productItem text-center" data-id="<%= product.id %>">
            <%= form_tag populate_orders_path, data: {method: :post, remote: true} do %>
                <%= image_tag url_for(product.image), width: 148, height: 148 if product.image.attached? %>
                <div class="productFooter">
                  <b><%= product.name %>
                    ₺<%= product.price %>
                  </b>
                </div>
                <%= hidden_field_tag :product_id, product.id %>
            <% end %>
          </div>
        </li>
    <% end %>
  </ul>

</div>
<div class="cartContainer">
  <%= render partial: 'orders/cart' %>
</div><!--/span-->


<script type="text/javascript" charset="utf-8">
  var idleTime = 0;

  $(document).on('mousemove', function () {
    idleTime = 0;
  });

  if (typeof(cartCheck) != 'undefined') {
    clearInterval(cartCheck);
  }

  cartCheck = setInterval(function () {
    if (idleTime > 45) {
      idleTime = -2000000;
      show_loading();
      $.get('/home/reset_cart.js');
    }
    idleTime += 1;
  }, 1000)


</script>

app/views/home/login.html.erb
<div class="container" style="margin-top: 100px;">

  <div class="text-center">
    <h1>  Kartınızı okutunuz </h1>
    <hr>
    <%= form_tag login_home_path, data: {method: :post}, class: 'autosubmit disable' do %>
    <div class="readerPreview">
      <%= image_tag 'rfid.png', width: 200 %>
    </div>
    <% if params[:card].present? %>
      <%= text_field_tag :card, params[:card], id: 'card' %>
      <%= submit_tag 'Giriş' %>
      <% else %>
      <%= hidden_field_tag :card, params[:card], id: 'card' %>
      <% end %>
      <% end %>
      <%= link_to 'Vazgeç', root_path, class: 'btn btn-default' %>
    </div>

    <%= render partial: '/shared/reader', locals: {auto_submit: true} %>

  </div>

app/views/home/publish_backup.text.erb
ok

app/views/home/publish_number.text.erb
ok

app/views/home/read.js.erb
<% if @response.present? %>
$("#card").val("<%= @response %>");
<% if params[:auto_submit] %>
show_loading();
$('form').submit();
<% end %>
<% else %>
//window.location.href = '/';
<% end %>

app/views/home/reset_cart.js.erb
$("#cartArea").replaceWith("<%= j render partial: 'orders/cart', formats: [:html], handlers: [:erb] %>");
<% if @product_ids_to_show %>
<% @product_ids_to_show.each do |pid| %>
$("#product_<%= pid %>").show();
<% end %>
<% end %>
hide_loading();