config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  mount ActionCable.server => '/cable'

  root controller: :home, action: :index

  resource :admin, controller: 'admin' do
    get :auto_logout
  end

  resource :home, controller: 'home' do
    match :login, via: [:get, :post]
    delete :logout
    get :publish_number
    get :publish_backup
    get :reset_cart, format: :js
    get :read
    get :account_details
  end
  resources :account_activities

  resources :reports do
    collection do
      get :detailed_z_report
      get :zreport

    end
  end

  resources :line_items do
    member do
      post :cancel
    end
  end

  resources :orders do
    collection do
      post :complete
      post :populate
      delete :remove_item
    end
    member do
      post :cancel
      post :print
    end
  end
  resources :accounts
  resources :products do
    collection do
      post :update_positions
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account, required: false
  has_many :line_items
  has_many :account_activities, as: :source, dependent: :destroy
  after_destroy :update_account

  def self.not_canceled
    where(state: 'completed')
  end

  def self.completed
    where(state: 'completed')
  end

  def after_complete
    self.line_items.each(&:decrease_units)
    print
  end

  def print
    begin
      self.update_column(:printed_count, self.printed_count.to_i + 1)
      Printer.print(self)
    rescue

    end
  end

  def update_account
    refund_total
    self.account.update_balance
  end

  def refund_total
    account.
        account_activities.
        create!(
            amount: self.total.to_f,
            order_id: self.id,
            source: self,
            admin_id: Account.current.try(:id))
  end

  def name
    "Sipariş ##{self.id}"
  end

  def cancel!
    self.state = 'canceled'
    self.canceled_by = Account.current.try(:id)
    self.update!
    self.update_account # Refunds
    self.line_items.update_all(state: 'canceled')
    self.line_items.each(&:increase_units)
    self.update!
  end

  def canceled?
    self.state == 'canceled'
  end

  def update!
    self.total = self.line_items.not_canceled.sum(:total)
    self.save
  end

  def add_to_order(product_id)
    li = self.line_items.new(product_id: product_id)
    li.quantity = 1
    li.save
    li
  end

  #  authorize 'admin'
  #  authorize 'second_admin'
  #  authorize 'cashier'
  #  authorize! 'cashier'

  def authorize(required_role)
    self.send required_role.to_sym
  end

  def authorize!(required_role)
        unless authorize(required_role)
          raise Grocery::AccessDenied
        end
  end


  def order_display_text
    line_items.group(:product_id).pluck('sum(quantity) as quantity, product_id').collect do |quantity, pid |
      product = Product.find(pid)
      "#{quantity} #{product.name}"
    end.to_sentence
  end

  def grouped_items
    line_items.not_canceled.group(:product_id).pluck('sum(total), sum(quantity), product_id').collect do |li|
      {name: Product.where(id: li[2]).pluck(:name).first, count: li[1], total: li[0]}
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < AdminController
  skip_before_action :authorize_admin!, only: [:populate, :complete, :remove_item, :show, :print]
  skip_before_action :session_expiry, only: [:populate, :complete, :remove_item, :show]
  skip_before_action :update_activity_time, only: [:populate, :complete, :remove_item, :show]

  before_action :account_required!, only: [:show]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :cancel, :print]
  before_action :authorize_admin_cashier!, only: [:print]

  # GET /orders
  # GET /orders.json
  def index
    params[:q] ||= {}

    if (@current_account.cashier? or @current_account.second_admin?) && !@current_account.admin?
      params[:q][:completed_at_gteq] = 18.hours.ago
    end

    unless params[:all]
      params[:q][:state_cont] ||= 'completed'
    end

    if params[:q][:completed_at_cont].present?
      @date = params[:q][:completed_at_cont].to_date
      params[:q][:completed_at_gteq] = @date.beginning_of_day
      params[:q][:completed_at_lteq] = @date.end_of_day
      params[:q].delete :completed_at_cont
    end

    if params[:q][:state_cont] == "-1"
      params[:all] = true
      params[:q].delete :state_cont
    end

    @q = Order.where(state: ['completed', 'canceled']).ransack(params[:q])
    if request.format.xls?
      filename = "Siparişler_#{I18n.localize(Time.current, format: :custom)}.xls"
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
      @orders = @q.result(distinct: true).order(:completed_at => :desc)
    else
      @orders = @q.result(distinct: true).page(params[:page]).order(:completed_at => :desc)
      @page_total = Order.where(id: @orders.pluck(:id)).sum(&:total)
    end
  end

  def populate
    @order = current_order
    li = @order.add_to_order(params[:product_id])
    if li.product.count_on_hand <= @order.line_items.where(product_id: params[:product_id]).sum(:quantity)
      @li = li
    end
  end

  def remove_item
    @order = current_order
    if params[:empty]
      @product_ids_to_show = @order.line_items.pluck(:product_id)
      @order.line_items.destroy_all
    else
      @product_ids_to_show = @order.line_items.where(id: params[:line_item_id]).pluck(:product_id)
      @order.line_items.where(id: params[:line_item_id]).destroy_all
    end
    @order.update!
    render :populate
  end

  def complete
    # Start card listener
    # Cart listener will ping back here with account
    # If account id presents and it has enough balance, then complete the order
    # Decrease balances
    # Log request
    current_order

    redirect_to root_path and return if @order.line_items.blank?

    if params[:card].present?
      account = Account.where(card: params[:card]).first
      if account.blank?
        flash['warning'] = 'Kart tanımlanamadı...'
        redirect_to root_path and return
      end
      # Admin can add expense to any account.
      if (account.has_special_role?) && params[:account_id].present?
        admin_account = account
        account = Account.where(id: params[:account_id]).first
      end

      if account and account.enough_balance?(@order.total.to_f)
        begin
          Order.transaction do
            @order.account = account
            @order.completed_at = Time.now
            @order.state = 'completed'
            account.balance = account.balance.to_f - @order.total.to_f
            account.save!
            account.account_activities.create!(amount: @order.total.to_f * -1, order_id: @order.id, source: @order, admin_id: admin_account.try(:id))
            @order.save!
            @order.after_complete
          end
          session[:order_id] = nil
          flash[:success] = "#{account.name} ₺#{@order.total} Ödeme alındı. Kalan bakiyeniz: ₺ #{account.balance.to_f.round(2)}"
          redirect_to root_path
        rescue Exception => e
          # Stop listener
          flash[:error] = "Hata - #{e.message}"
          redirect_to root_path
        ensure
          #stop listener
        end
      else
        flash[:error] = "Bakiye yetersiz. Bakiyeniz: ₺ #{account.try(:balance).to_f.round(2)}"
        redirect_to root_path
        # Stop listener
      end
    end

    # r = `sudo python rfidreader.py`
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    unless @current_account.can_manage_order?
      @order = @current_account.orders.where(id: params[:id]).first
      redirect_to root_path and return if @order.blank?
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def print
    @order.print
    flash[:success] = "Yazdırılıyor..."
    redirect_to order_path(@order)
  end

  def cancel
    @order.cancel!
    flash[:success] = "İptal edildi"
    redirect_to order_path(@order)
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:account_id, :total, :completed_at)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_cart.html.erb
<div id="cartArea" class="">
  <% if @order.present? && @order.line_items.present? %>
      <h3>Sipariş detayı
        <small class="pull-right">
          <%= link_to 'Temizle', remove_item_orders_path(empty: 1), data: {method: :delete, remote: true}, class: 'btn btn-info btn-sm btn-flat' %>
        </small>
      </h3>
      <div class="scrollableArea marB30">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th>Ürün</th>
            <th>Tutar</th>
            <th>Sil</th>
          </tr>
          </thead>
          <tbody>

          <% @order.line_items.includes(:product).each do |li| %>
              <tr>
                <td><%= li.product.name %>
                  <%= form_for li , remote: true do |f| %>
                         <%= f.select :quantity, options_for_select(1..(li.product.count_on_hand.to_i), selected: f.object.quantity), {}, class: 'quantity-select' %>
                  <% end %>
                </td>
                <td><b>₺<%= li.total %></b></td>
                <td><%= link_to 'X', remove_item_orders_path(line_item_id: li.id), data: {method: :delete, remote: true}, class: 'btn btn-default btn-sm btn-flat' %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="cartAction">
        <div class="cartTotal">
          <b class="pull-left f-s-16">Toplam</b>
          <b class="pull-right f-s-16">₺ <%= @order.total %></b>
        </div>
        <%= form_tag complete_orders_path, method: :post, class: 'autosubmit disable' do %>
            <%= submit_tag 'Ödeme Yap', class: 'btn btn-primary btn-block btn-flat btn-lg' %>
        <% end %>

      </div>
  <% else %>
      <h3>Sepetiniz Boş</h3>
      <div class="scrollableArea marB30">
        <div class="emptyCartContent">
          <span><i class="fa fa-shopping-basket" style="font-size: 24px;"></i></span>
          <span>&nbsp; Ürün seçiniz</span>
        </div>
      </div>
      <div class="cartAction">
        <div class="cartTotal">
          <b class="pull-left f-s-16">Toplam</b>
          <b class="pull-right f-s-16">₺ 0.0</b>
        </div>
        <%= form_tag complete_orders_path, method: :post do %>
            <%= submit_tag 'Ödeme Yap', class: 'btn btn-primary btn-block btn-flat btn-lg', disabled: true %>
        <% end %>
      </div>
  <% end %>
</div><!--/.well -->

<script type="text/javascript" charset="utf-8">
  hide_loading();

  $("a[data-remote='true']").on('click', function (e) {
    get_loading_container();
    show_loading();
  });

  $('form').on('submit', function () {
    get_loading_container();
    show_loading();
  });

</script>

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :account_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :account_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:account_id) %>
  </div>
  <div class="form-group">
    <%= f.label :total, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :total, :class => 'form-control' %>
    </div>
    <%=f.error_span(:total) %>
  </div>
  <div class="form-group">
    <%= f.label :completed_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :completed_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:completed_at) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/orders/complete.html.erb
<div class="container" style="margin-top: 100px;">
  <div class="text-center">
    <h1> Ödemeyi tamamlamak için kartınızı okutunuz</h1>
    <hr>
    <h3><b><%= @order.order_display_text %></b></h3>
    <b class="cartTotal" style="font-size: 24px;
        line-height: 20px;">Toplam: ₺ <%= @order.total %></b>
    <hr>
    <%= form_tag complete_orders_path, data: {method: :post}, class: 'autosubmit disable' do %>
        <div class="readerPreview">
          <%= image_tag 'rfid.png', width: 200 %>
        </div>
        <%= hidden_field_tag :card, params[:card], id: 'card' %>
        <% if params[:admin] %>
            <%= hidden_field_tag :admin, params[:admin] %>
            <p>Ödemenin çekileceği üye hesabını seçiniz ve kartınızı okutunuz.</p>
            <%= select_tag :account_id, options_for_select(Account.active.order(:name).pluck(:name, :id)), {prompt: 'Hesap Seçiniz', class: 'accountSelect'} %>
        <% end %>
    <% end %>
    <%= link_to 'Vazgeç', root_path, class: 'btn btn-default marT20' %>
    <%= content_for :links do %>
        <li><%= link_to 'Yönetici Giriş', complete_orders_path(admin: 1), data: {method: :post}, class: '' %></li>
    <% end %>
  </div>
  <%= render partial: '/shared/reader', locals: {auto_submit: true} %>
</div>


<script type="text/javascript" charset="utf-8">
  <% if params[:admin] %>

  $(function () {
    $('.autosubmit').removeClass('autosubmit');
    $('.accountSelect').on('change', function () {
      if ($(this).val().length > 0) {
        $('form').addClass('autosubmit')
      } else {
        $('form').removeClass('autosubmit')
      }
    });
  });
  <% end %>

</script>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
  <div class="clearfix">
  </div>
</div>


<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th colspan="5">
        <%= search_form_for @q, class: 'form-inline' do |f| %>
        <%= f.select :account_id_eq, options_for_select(Account.active.order(:name).pluck(:name, :id), selected: params[:q][:account_id_eq]), {include_blank: 'Hesap Seçiniz'}, class: 'form-control' %>
        <%= f.search_field :line_items_product_name_cont, placeholder: 'Ürün İsmi', class: 'form-control' %>
        <%= f.search_field :completed_at_cont, placeholder: 'Tarih',  value: (I18n.localize(@date) rescue ''), autocomplete: 'off', class: 'form-control datepicker' %>
        <%= f.select :state_cont, options_for_select([['Tümü', '-1'], ['Tamamlanmış', 'completed'], ['İptal', 'canceled']], selected: params[:q][:state_cont]),{}, class: 'form-control' %>
        <%= f.submit 'Ara', class: 'btn btn-default' %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%= t :completed_at %></th>
      <th><%= t :created_at %></th>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= link_to order.id, order_path(order) %>
        <% if order.canceled? %>
        <span class="label label-danger">İptal</span>
        <% else %>
        <span class="label label-success">Tamamlanmış</span>
        <% end %>
      </td>
      <td><%= order.account.try(:name) %></td>
      <td>₺<%= order.total %></td>
      <td><%= l order.completed_at %></td>
      <td><%= l order.created_at %></td>
      <td>
        <%= link_to 'Detay',
        order_path(order, return_to: orders_path), :class => 'btn btn-default btn-xs' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders, :theme => 'twitter-bootstrap-3' %>
<br>
<%= page_entries_info @orders %>
<br>
<%= link_to url_for({:only_path => false, format: :xls}.merge(params.permit!)), target: '_blank' do %>
Excel'e aktar
<% end %>

<br>

Sayfa toplamı: ₺<%= @page_total.to_f.round(2) %>

app/views/orders/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <Style ss:ID="Default" ss:Name="Normal">
      <Alignment ss:Vertical="Bottom"/>
      <Borders/>
      <Font ss:FontName="Calibri" x:CharSet="204" x:Family="Swiss" ss:Size="12"
      ss:Color="#000000"/>
      <Interior/>
      <NumberFormat/>
      <Protection/>
    </Style>
    <Style ss:ID="s62">
      <Interior ss:Color="#FCF305" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="s63">
      <Font ss:FontName="Calibri" x:CharSet="204" x:Family="Swiss" ss:Size="12"
      ss:Color="#000000" ss:Bold="1"/>
    </Style>
    <Style ss:ID="s64">
      <NumberFormat ss:Format="#,##0.00\ &quot;TRY&quot;;[Red]#,##0.00\ &quot;TRY&quot;"/>
    </Style>
    <Style ss:ID="s65">
      <NumberFormat ss:Format="Short Date"/>
    </Style>
  </Styles>

  <Worksheet ss:Name="Sheet1">
  <Table>
      <Row>
        <Cell ss:StyleID="s63"><Data ss:Type="String">ID</Data></Cell>
        <Cell ss:StyleID="s63"><Data ss:Type="String">Hesap</Data></Cell>
        <Cell ss:StyleID="s63"><Data ss:Type="String">Toplam</Data></Cell>
        <Cell ss:StyleID="s63"><Data ss:Type="String">Tarih</Data></Cell>
      </Row>
      <% @orders.each do |order| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= order.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= order.account.try(:name) %></Data></Cell>
            <Cell ss:StyleID="s64"><Data ss:Type="Number"><%= order.total %></Data></Cell>
            <Cell><Data ss:Type="String"><%= l order.completed_at %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/populate.js.erb
$("#cartArea").replaceWith("<%= j render partial: 'cart', formats: [:html], handlers: [:erb] %>");


<% if @li %>
$("#product_<%= @li.product_id %>").hide();
<% elsif @product_ids_to_show %>

<% @product_ids_to_show.each do |pid| %>
$("#product_<%= pid %>").show();
<% end %>
<% end %>

setTimeout(hide_loading, 500);

app/views/orders/show.html.erb
<div class="page-header">
  <h1>Sipariş detayı</h1>
  <div class="clearfix"></div>
</div>

<div class="col-lg-12">
  <table class="table table-striped table-bordered text-right table-hover">
    <tbody>
    <tr>
      <td colspan="3">
        <% if @order.canceled? %>
            <small class="label label-danger"><%= Account.where(id: @order.canceled_by).pluck(:name).to_sentence %>
              Tarafından İptal Edilmiş
            </small>
        <% elsif @current_account.can_cancel? %>
            <%= link_to 'Siparişi İptal Et',
                        cancel_order_path(@order),
                        :method => :post,
                        :data => {:confirm => 'Bakiye geri yüklenecek. Onaylıyor musunuz?'},
                        :class => 'btn btn-xs btn-danger pull-right' %>

        <% end %>

        <% if !@order.canceled? && @current_account.can_print? %>
        <%= link_to print_order_path(@order),
                    :data => {:confirm => 'Yazdırılacak, onaylıyor musunuz?'},
                    :method => :post, :class => 'btn btn-xs info pull-left' do %>
            <i class="fa fa-print"></i>
        <% end %>
        <% end %>


      </td>
    </tr>

    <tr>
      <td colspan="3">
        <b class="pull-left"><%= @order.account.try(:name) %></b>
        <span class="pull-right"><%= l @order.completed_at, format: :long %></span>
      </td>
    </tr>
    <tr style="font-size: 16px;">
      <td><b>Ürün</b></td>
      <td class="text-right"><b>Adet</b></td>
      <td class="text-right"><b>Fiyat</b></td>
    </tr>
    <% @order.line_items.each do |li| %>
        <tr>
          <td>
            <%= li.product.try(:name) %>
            <% unless li.canceled? %>
                <%= link_to 'Ürünü İptal Et', cancel_line_item_path(li), data: {method: :post, confirm: 'Emin misiniz?'}, class: 'btn btn-default btn-xs pull-left' if @current_account.can_cancel? %>
            <% else %>
                <span class="label label-danger pull-left">İptal Edilmiş</span>
            <% end %>
          </td>
          <td class="text-right"><%= li.quantity %> Adet</td>
          <td class="text-right">₺<%= li.total %></td>
        </tr>
    <% end %>
    <tr style="font-size: 16px;">
      <td colspan="2" class="text-right"><b>Toplam:</b></td>
      <td class="text-right"><b>₺<%= @order.total %></b></td>
    </tr>

    </tbody>
  </table>
</div>



<%= link_to 'Geri',
            (params[:return_to] || :back),
            :class => 'btn btn-default' %>