config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  mount ActionCable.server => '/cable'

  root controller: :home, action: :index

  resource :admin, controller: 'admin' do
    get :auto_logout
  end

  resource :home, controller: 'home' do
    match :login, via: [:get, :post]
    delete :logout
    get :publish_number
    get :publish_backup
    get :reset_cart, format: :js
    get :read
    get :account_details
  end
  resources :account_activities

  resources :reports do
    collection do
      get :detailed_z_report
      get :zreport

    end
  end

  resources :line_items do
    member do
      post :cancel
    end
  end

  resources :orders do
    collection do
      post :complete
      post :populate
      delete :remove_item
    end
    member do
      post :cancel
      post :print
    end
  end
  resources :accounts
  resources :products do
    collection do
      post :update_positions
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= action_cable_meta_tag %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "GroceryRpi" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <script>
    setInterval(function () {
      var dt = new Date();
      document.getElementById("datetime").innerHTML = dt.toLocaleString();
    }, 1000);

    <% if @logged_in %>
    setInterval(function () {
      $.get('/admin/auto_logout.js')
    }, 61000);
    <% end %>
  </script>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="loader-big" id="loader">
  <div class="load-content text-center">
    <svg width="38" id="newHRLoader" height="38" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg">
      <g fill="none" fill-rule="evenodd">
        <g transform="translate(1 1)" stroke-width="2">
          <circle stroke-opacity=".5" cx="18" cy="18" r="18"/>
          <path d="M36 18c0-9.94-8.06-18-18-18">
            <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"/>
          </path>
        </g>
      </g>
    </svg>
    <p class="LContent loader_content" id="loaderMessage">
      <%= local_assigns[:message] %>
    </p>
  </div>
</div>

<div class="<%= @logged_in ? 'container' : 'mainContainer' %>">
  <%= bootstrap_flash %>
  <%= yield %>
</div> <!-- /container -->
<div class="footer">
  <div class="">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="pull-left" style="margin-top: 5px;" href="/">
      <%= image_tag 'logo.png', width: 200 %>
    </a>
    <span id="datetime"></span>

    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <% if @current_account %>
            <% if @current_account.admin? %>
            <li><%= link_to "Bakiye Yükle", new_account_activity_path %></li>
                <li><%= link_to "Hesaplar", accounts_path %></li>
                <li><%= link_to "Bakiye Hareketleri", account_activities_path %></li>
                <li><%= link_to "Siparişler", orders_path %></li>
                <li><%= link_to "Ürünler", products_path %></li>
                <li><%= link_to "Z Raporu", zreport_reports_path %></li>
            <% elsif @current_account.second_admin? %>
            <li><%= link_to "Bakiye Yükle", new_account_activity_path %></li>
                <li><%= link_to "Bakiye Hareketleri", account_activities_path %></li>
                <li><%= link_to "Siparişler", orders_path %></li>
                <li><%= link_to "Z Raporu", zreport_reports_path %></li>
            <% elsif @current_account.cashier? %>
            <li><%= link_to "Bakiye Yükle", new_account_activity_path %></li>
                <li><%= link_to "Bakiye İşlemlerin", account_activities_path %></li>
            <% end %>

            <li><%= link_to "#{@current_account.name} (Hesabım)", account_details_home_path %></li>
            <li><%= link_to "Çıkış", logout_home_path, data: {method: :delete}, class: 'pull-right', onclick: 'show_loading();' %></li>
        <% else %>
            <li><%= link_to "Giriş", login_home_path %></li>
        <% end %>
        <%= yield :links %>
      </ul>
    </div>
  </div>
</div>
</body>
</html>